services:
  backend:
    build:
      context: ./backend
    container_name: halyk-health-backend
    restart: unless-stopped
    env_file:
      - path: ./backend/.env
        required: false
    ports:
      - "4000:4000"
    command: sh -c "npm run start"
